### PR TITLE
Fix #254

### LINKED ISSUE #254: Bug: RSA key can't work
* reading API docs: https://github.com/intel/ehsm/blob/main/docs/API_Reference.md#createkey
* reason `flag --padding_mode doesn't correctly work.`

Example:
``` shell
# 1.
cd ehsm && ./run_with_single.sh

cd test/cli

# 2.  here return success
python3 createkey.py --url  https://127.0.0.1:9002 --keyspec EH_RSA_4096  --origin EH_INTERNAL_KEY --padding_mode EH_PAD_RSA_PKCS1
```
image

``` shell
# 3.
python3 asymmetric_encrypt.py  --url https://127.0.0.1:9002 --keyid  0c96e815-6969-47f1-ac9b-03ba0c5fa888  --data MTIzNA==

```
image

### PR DESCRIPTION
**Pull request by nntp4**
close #254

### CODE REVIEW

**Review by syan10 — APPROVED** [review]

**Comment by syan10** [comment]
Thanks for your contribution. :)

**Comment by yang8621** [comment]
Could rebase your code base and push again?  Thanks.

**Comment by nntp4** [comment]
> Could rebase your code base and push again? Thanks.

@yang8621  done

**Comment by yang8621** [comment]
I think your patch is OK.  But the full unit test cannot pass. You can also try: 

cd test
python3 test_kms_with_cli.py --url https://<ip_addr>:<port>

**Comment by nntp4** [comment]
> I think your patch is OK. But the full unit test cannot pass. There should be some existing inside code issues. You can also try:
> 
> cd test python3 test_kms_with_cli.py --url https://<ip_addr>:

I found that the issue was caused by ehsm_km_service can't connect to CouchDB.  sometimes Docker container is started but CouchDB is unavailable. To resolve this, I have added a check to the shell script. @yang8621

**Comment by yang8621** [comment]
> > I think your patch is OK. But the full unit test cannot pass. There should be some existing inside code issues. You can also try:
> > cd test python3 test_kms_with_cli.py --url https://<ip_addr>:
> 
> I found that the issue was caused by ehsm_km_service can't connect to CouchDB. sometimes Docker container is started but CouchDB is unavailable. To resolve this, I have added a check to the shell script. @yang8621

Do you mind sending an email to me?  yang.huang@intel.com

**Pull request merged**
